Fix as std::isnan does not cast arg to double. On windows cmath.h implementation std::isnan expects a double. static_cast<double> added to resolve compilation error C2668 'fpclassify': ambiguous call to overloaded function