fix: correct `metrics` argument format in model.compile (#280)
Resolved a ValueError caused by passing a single metric object to the `metrics` argument of `model.compile`. Updated it to a list containing `tf.keras.metrics.BinaryAccuracy` to comply with Keras requirements.

Error message:
ValueError: Expected `metrics` argument to be a list, tuple, or dict.